# Generated by Django 2.1.5 on 2019-02-06 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 8, 16, 24, 372639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueadded',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 8, 16, 24, 377690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenuespent',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 8, 16, 24, 378045, tzinfo=utc)),
        ),
    ]
