# Generated by Django 2.1.3 on 2019-02-06 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20190206_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 14, 32, 17, 285899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueadded',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 14, 32, 17, 286239, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenuespent',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 2, 6, 14, 32, 17, 286585, tzinfo=utc)),
        ),
    ]
