# Generated by Django 2.1.5 on 2019-02-07 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20190206_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 4, 55, 11, 417713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueadded',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 4, 55, 11, 418293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenuespent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 4, 55, 11, 418697, tzinfo=utc)),
        ),
    ]
