# Generated by Django 2.1.5 on 2019-02-07 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20190207_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 5, 2, 8, 6202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenueadded',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 5, 2, 8, 6719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revenuespent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 5, 2, 8, 7234, tzinfo=utc)),
        ),
    ]
