# Generated by Django 2.1.5 on 2019-02-06 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grades', models.TextField()),
                ('ambition', models.TextField()),
                ('joined', models.DateTimeField(default=datetime.datetime(2019, 2, 6, 8, 7, 30, 325681, tzinfo=utc))),
            ],
        ),
    ]
