# Generated by Django 2.1.3 on 2019-02-06 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20190206_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 13, 54, 2, 337488, tzinfo=utc)),
        ),
    ]
