# Generated by Django 2.1.3 on 2019-02-06 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20190206_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='village',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='child',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 14, 4, 26, 154800, tzinfo=utc)),
        ),
    ]
