# Generated by Django 2.1.3 on 2019-02-06 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20190206_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 14, 32, 17, 287052, tzinfo=utc)),
        ),
    ]
