# Generated by Django 2.1.5 on 2019-02-07 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_auto_20190206_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='mentor',
            field=models.CharField(default='Mahesh Singh', max_length=255),
        ),
        migrations.AlterField(
            model_name='child',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 4, 55, 11, 419245, tzinfo=utc)),
        ),
    ]
