# Generated by Django 2.1.5 on 2019-02-07 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_auto_20190207_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='scholarships',
            field=models.CharField(default='360', max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 5, 2, 8, 7972, tzinfo=utc)),
        ),
    ]
